server:
  port: ${SERVER_PORT:8761}
spring:
  application:
    name: eureka
eureka:
  client:
    registerWithEureka: false   #Eureka서버 자신을 Service Registry에 등록할지 여부. 복수서버면 true
    fetchRegistry: false        #Service registry를 다른 곳에서 가져올 지 여부. 복수서버면 true
    serviceUrl:
      # 여러대의 Eureka서버가 있는 경우 반드시 자신을 제외한 다른 Eureka서버 주소(들)만 지정해야 함
      # k8s배포시에는 service오브젝트 이용하여 설정하면 자동으로 자신을 제외한 다른 서버를 찾음
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  server:
    enableSelfPreservation: true    #등록된 service의 일시적 장애일때 service registry에서 제거 안함
    eviction-interval-timer-in-ms: 10000  #지정된 시간마다 유효하지 않은 service를 service registry에서 제거
